### PR TITLE
adding video support

### PR DESCRIPTION
**Pull request by jrassa**
I have also done an initial update to your theme tutorial on the wiki to cover supporting video.

### CODE REVIEW

**Comment by mattrixk** [comment]
It looks like there are a few problems:

video

- the screenshot is tiny
- the video doesn't display (but can still be heard)
- the marquee is under the System Logo. It looks like "md_marquee" doesn't have any size or positioning code in spare.xml

I unfortunately don't have the time to fix it at the moment (I'm checking this on my lunch break at work).

**Comment by jrassa** [comment]
Pushed an update.  Sorry about that.  I don't have marquees scraped on my dev box so I was using md_image as a placeholder and forgot to switch it back.

**Comment by mattrixk** [comment]
The marquee looks good, but the video still isn't showing up. It's most likely because the background images aren't called "background", and have an extra="true" tag.

**Comment by jrassa** [comment]
The video shows up on newer versions of ES with z-index support.  The problem is that the initial video support didn't work well with themes that used multiple background images as this theme does.

**Comment by mattrixk** [comment]
Ahh, fair enough. I'll have to try it out on a newer version. I have one of
your windows versions with the z-index stuff in it somewhere around here. I
was using it to make an updated version of the Toolkit before I got
distracted by real life.

**Pull request closed without merging**
